# Generated by Django 6.0 on 2026-06-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_channel',
            field=models.URLField(blank=True, help_text='Full WhatsApp Channel link e.g. https://whatsapp.com/channel/xxx'),
        ),
    ]
