# Generated by Django 6.0 on 2026-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0002_subscriber_sitesettings_whatsapp_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to='variant_images/'),
        ),
    ]
