# Generated by Django 6.0 on 2026-06-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0003_alter_variantimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_yards',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='min_yards',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
