# Generated by Django 6.0 on 2026-06-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0004_product_max_yards_product_min_yards'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cj_pid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cj_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
