# Generated by Django 6.0 on 2026-06-24 14:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0005_product_cj_pid_product_is_cj_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
